config/routes.rb
QuestionnaireSite::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    delete "sign_out", :to => "devise/sessions#destroy"
    get "login", :to => "devise/sessions#new"
  end

  devise_for :admins, :path => "admin", :controllers => { :sessions => "admin/sessions" }

  get "home/index"
  get "home/map", :as  => :map
  post "home/update_address", :as  => :update_address
  match "canvas" => "canvas#index"

  match "/contacts/:importer/callback" => "email_invites#contacts_callback", :as => :contacts_callback
  match "/contacts/failure" => "email_invites#contacts_callback_failure", :as => :contacts_callback_failure
  mount Resque::Server, :at => "/resque"

  get "find" => 'search#index', :as => :find

  resources :search do
    collection do
      match :change_range
    end
  end

  resources :reviews do
    member do
      get :repost, :reject
    end
  end
  resources :users do
    member do
      get :following_followers, :address_toggle
    end
  end
  resources :friend_relations, :only => [:create, :destroy]
  resources :email_invites do
    collection do
      get :confirm
      post :invitation_form
      post :outlook_import
    end
  end

  root :to => "home#index"

  namespace :admin do
    resource :profile, :only => [:edit, :update]

    resources :users
    resources :categories
    resources :reviews

    root :to => "users#index"
  end

end

app/controllers/search_controller.rb
class SearchController < FrontEndController

  before_filter :with_google_maps_api
  before_filter :default_miles_range
  before_filter :load_data_for_checkbox
  before_filter :fix_params, :only => :create

  def index
    @review = Review.new
  end

  def create
    @review = Review.new params[:review]
    @reviews = Review.scoped_by_search_params(params, current_user)
    render :action => :index
  end

  def change_range
    current_range = (params[:current_range] || default_range).to_i
    cookies[:kms_range] = new_range(current_range)
    redirect_to :action => :index
  end

  protected

  def default_miles_range
    @kms_range = (cookies[:kms_range] || default_range).to_i
  end

  private

  def fix_params
    params[:review] ||= {}
    params[:review][:search_ids] ||= []
    params[:review][:search_ids].reject!(&:blank?)
  end

  def load_data_for_checkbox
    categories = Category.fetch_all.map{|c| [c.name, "category_#{c.id}"] }    
    users_in_my_area = User.within(default_range, :origin => current_user)
    followers = users_in_my_area.followers_for(current_user)
    following = users_in_my_area.following_by(current_user)
    other = users_in_my_area - followers - following - [current_user]

    [followers, following, other].each do |users|
      users.map!{ |u| [u.front_name.to_s + '|' + u.city.to_s, "user_#{u.id}"] }
    end

    @data = [[I18n.t('search.group.category'), categories], 
             [I18n.t('search.group.followers_in'), followers],
             [I18n.t('search.group.following_in'), following],
             [I18n.t('search.group.other_people'), other]]
  end

  def default_range
    20
  end

  def new_range(old_range)
    {20 => 10, 10 => 20}[old_range]
  end

end

app/helpers/search_helper.rb
module SearchHelper

  def grouped_and_sorted_by_distance(reviews)
    my_area = []
    outside_area = []
    reviews.each do |review|
      distance = current_user.distance_to(review.user)
      # review.distance = distance
      distance <= @kms_range ? (my_area << review) : (outside_area << review)
    end
    return my_area, outside_area
  end

  def grouped_by_owner(my_area_reviews)
    my_reviews = []
    followers_reviews = []
    following_reviews = []
    others_reviews = []

    my_area_reviews.each do |review|
      if current_user.id == review.user_id
        my_reviews << review
      elsif User.followers_for(current_user).pluck(:id).include? review.user_id
        followers_reviews << review
      elsif User.following_by(current_user).pluck(:id).include? review.user_id
        following_reviews << review
      else
        others_reviews << review
      end
    end
    return my_reviews, followers_reviews, following_reviews, others_reviews
  end

end

app/views/search/_grouped_reviews.html.erb
<% if reviews.present? %>
    <div class='area'>
      <h4><%= title %></h4>
      <% reviews.each do |review| %>
        <%= render 'review', :review => review %>
      <% end %>
    </div>
<% end %>

app/views/search/_review.html.erb
<div class="review breadcrumb" id="review_<%=review.id%>">

  <div class="left-part">
    <%= fb_avatar(review.user) %>
  </div>

  <div class="right-part">
    <p>
      <%= link_to review.user.front_name, user_path(review.user) %> / <%= review.categories_list %>
    </p>
    <p>
      <%= t('find_something.review.name') %><%= review.name %>
    </p>
    <p>
      <%= t('find_something.review.address') %><%= review.address %>
    </p>
    <p>
      <%= t('find_something.review.phone') %><%= review.phone %>
    </p>
    
    <div class="review-text">
      <%= review.comment %>
    </div>
    <%= render 'reviews/add_to_your_page', :review => review  unless current_user == review.user %>
  </div>

  <div class="clearfix"></div>

  <hr style="margin: 0 30px;"/>

</div>

app/views/search/_reviews.html.erb
<% my_area_reviews, outside_area_reviews = grouped_and_sorted_by_distance(@reviews) %>
<% my_reviews, followers_reviews, following_reviews, others_reviews = grouped_by_owner(my_area_reviews)  if my_area_reviews.present?%>

<%= render 'grouped_reviews', :reviews => my_reviews, :title => t('find_something.my_reviews_title') %>
<%= render 'grouped_reviews', :reviews => followers_reviews, :title => t('find_something.followers_reviews_title') %>
<%= render 'grouped_reviews', :reviews => following_reviews, :title => t('find_something.following_reviews_title') %>
<%= render 'grouped_reviews', :reviews => others_reviews, :title => t('find_something.others_reviews_title') %>

app/views/search/index.html.erb
<div class='find-something'>

  <div class="greetings">
    <%= I18n.t('find_something.greetings', :km => @kms_range) %><br/>
    <%= link_to I18n.t("find_something.change_range_#{@kms_range}"), change_range_search_index_path(:current_range => @kms_range) %>
  </div>


  <div class="search-area">

    <div class='search-box'>
      <%#= simple_form_for @review, :url => search_index_path, :method => :post, :html => { :class => 'form-horizontal'} do |f| %>

        <%#= f.input :search_ids, :collection => @data, :as => :grouped_chosen, 
                    :group_method => :last, :prompt => false,
                    :input_html => { :class => 'span5', :multiple => true }, 
                    :label => t('find_something.search_label'), 
                    :placeholder => t('find_something.search_placeholder') %>

        <%#= f.button :submit, :value => t('find_something.button_text'), :class => 'btn-primary search-button' %>

      <%# end %>
    </div> 
    <div class="clearfix"></div>

    <div id="map_canvas"></div>

    <div class="clearfix"></div>

  </div> 

  <%= render 'reviews' if @reviews %>

 </div>

<script type="text/javascript">
  var map;
  var markers = [];

  function initialize_google_maps() {
    var currentlatlng = new google.maps.LatLng(<%= current_user.lat %>, <%= current_user.lng %>);
    var zoom = <%#= @kms_range %> > 10 ? 10 : 11;
    var myOptions = {
        zoom: zoom,
        center: currentlatlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP, // ROADMAP, SATELLITE, HYBRID
        streetViewControl: false
    };
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

    var marker = new google.maps.Marker({map: map, position: currentlatlng});
    map.setCenter(currentlatlng);
    map.setZoom(zoom);

    var circle = new google.maps.Circle({
        map: map,
        fillOpacity: 0,
        strokeWeight: 2,
        strokeOpacity: 0.7,
        radius: <%#= @kms_range %>*1000,
    });
    circle.bindTo('center', marker, 'position');

  }

  function show_markers() {
    if (markers)
      for(i in markers) {
        markers[i].setMap(map);
      }
  }

  function add_marker(location) {
    marker = new google.maps.Marker({
      position: location,
      map: map
    });
    markers.push(marker);
  }

  function initialize_markers() {
    <%# (@reviews || []).each do |r| %>
      <%# next unless r.lat && r.lng %>
      position = new google.maps.LatLng(<%#= r.lat %>, <%#= r.lng %>);
      add_marker(position);
    <%# end %>
  }

  $(function() {
    initialize_google_maps();
    initialize_markers();
    show_markers();
  });

</script>