config/routes.rb
QuestionnaireSite::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    delete "sign_out", :to => "devise/sessions#destroy"
    get "login", :to => "devise/sessions#new"
  end

  devise_for :admins, :path => "admin", :controllers => { :sessions => "admin/sessions" }

  get "home/index"
  get "home/map", :as  => :map
  post "home/update_address", :as  => :update_address
  match "canvas" => "canvas#index"

  match "/contacts/:importer/callback" => "email_invites#contacts_callback", :as => :contacts_callback
  match "/contacts/failure" => "email_invites#contacts_callback_failure", :as => :contacts_callback_failure
  mount Resque::Server, :at => "/resque"

  get "find" => 'search#index', :as => :find

  resources :search do
    collection do
      match :change_range
    end
  end

  resources :reviews do
    member do
      get :repost, :reject
    end
  end
  resources :users do
    member do
      get :following_followers, :address_toggle
    end
  end
  resources :friend_relations, :only => [:create, :destroy]
  resources :email_invites do
    collection do
      get :confirm
      post :invitation_form
      post :outlook_import
    end
  end

  root :to => "home#index"

  namespace :admin do
    resource :profile, :only => [:edit, :update]

    resources :users
    resources :categories
    resources :reviews

    root :to => "users#index"
  end

end

app/helpers/admin/layout_helper.rb
module Admin::LayoutHelper

  # Gets title for admin area.
  #
  def admin_area_title
    "#{I18n.t('application.title')} :: #{I18n.t('application.admin_area')}"
  end

  # Renders navigation item for top admin menu.
  #
  # @param section [Symbol] navigation section appropriate to this item. See Admin::BaseController.navigation_section.
  #                         Uses to determines whether item should be highlighted as active.
  # @param path [String] menu item navigation path.
  #
  # @return [String] html markup.
  #
  def navigation_item(section, path)
    content_tag(:li, link_to(I18n.t("admin.sections.#{section}"), path), :class => (section == @navigation_section) ? 'active' : '')
  end
end

app/views/layouts/admin/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to admin_area_title, admin_root_path, :class => 'brand' %>
      <% if admin_signed_in? %>
        <div class="container nav-collapse">
          <ul class="nav">
            <%= navigation_item(:users, admin_users_path) %>
            <%= navigation_item(:categories, admin_categories_path) %>
            <%= navigation_item(:reviews, admin_reviews_path) %>
          </ul>

          <ul class="nav pull-right">
            <li><%= link_to t('helpers.links.go_to_website'), root_path, :target => '_blank' %></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-user icon-white"></i> <%= current_admin %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <%= link_to "Profile", edit_admin_profile_path %>
                <%= link_to t('helpers.links.sign_out'), destroy_admin_session_path, :method => 'delete' %>
              </ul>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : admin_area_title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "admin/application", :media => "all" %>
    <%= javascript_include_tag "admin/application" %>
    <% if @include_goole_maps %>
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true&libraries=places"></script>
    <% end %>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <link href="/assets/favicon.ico" rel="shortcut icon">
  </head>
  <body>
    <div id="wrapper">
      <%= render :partial => 'layouts/admin/navigation' %>
      <div class="container">
        <div class="content">
          <%= render :partial => 'layouts/breadcrumbs' %>
          <%= render :partial => 'layouts/messages' %>
          <%= yield %>
        </div>
      </div>
      <div class="push"></div>
    </div>

    <footer>
      <div class="container">
        <p class="brand">&copy; Qustionnaire 2012</p>
      </div>
    </footer>
  </body>
</html>