config/routes.rb
QuestionnaireSite::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    delete "sign_out", :to => "devise/sessions#destroy"
    get "login", :to => "devise/sessions#new"
  end

  devise_for :admins, :path => "admin", :controllers => { :sessions => "admin/sessions" }

  get "home/index"
  get "home/map", :as  => :map
  post "home/update_address", :as  => :update_address
  match "canvas" => "canvas#index"

  match "/contacts/:importer/callback" => "email_invites#contacts_callback", :as => :contacts_callback
  match "/contacts/failure" => "email_invites#contacts_callback_failure", :as => :contacts_callback_failure
  mount Resque::Server, :at => "/resque"

  get "find" => 'search#index', :as => :find

  resources :search do
    collection do
      match :change_range
    end
  end

  resources :reviews do
    member do
      get :repost, :reject
    end
  end
  resources :users do
    member do
      get :following_followers, :address_toggle
    end
  end
  resources :friend_relations, :only => [:create, :destroy]
  resources :email_invites do
    collection do
      get :confirm
      post :invitation_form
      post :outlook_import
    end
  end

  root :to => "home#index"

  namespace :admin do
    resource :profile, :only => [:edit, :update]

    resources :users
    resources :categories
    resources :reviews

    root :to => "users#index"
  end

end

app/controllers/home_controller.rb
class HomeController < FrontEndController

  skip_before_filter :authenticate_user!, :only => :index
  before_filter :check_if_user_not_signed_in, :only => :index
  skip_before_filter :force_address_step, :only => [:index, :map, :update_address]

  before_filter :with_google_maps_api, :only => :map

  after_filter :update_distances_to_other_users, :only => :update_address

  #before_filter :load_data_for_checkbox



  def index
    render 'users/sessions/new', :layout => 'devise'
  end

  def map
    @review = Review.new
  end

  def update_address
    if params[:changed] == '1'
      current_user.update_attributes(params[:user]) 
      redirect_to landing_page
    else
      flash[:alert] = I18n.t('map.address_validation')
      redirect_to landing_page
    end
  end

  private

  def check_if_user_not_signed_in
    if user_signed_in?
      if current_user.registration_complete?
        redirect_to landing_page
      else
        redirect_to map_path
      end
    end
  end

  def update_distances_to_other_users
    FriendRelation.update_distances(current_user)
  end

end

app/helpers/home_helper.rb
module HomeHelper

  # Determines whether user completed his profile on registration or not
  #
  # def registration_complete?(user)
  #   self.address.present?
  # end	
end

app/views/home/index.html.erb
<div class="sign-in">

  <p><%= t('home.welcome') %></p>

  <% if OAUTH_CONFIG['facebook'] %>
    <p><%= fb_login_button(image_tag("fblogin.png")) %></p>
  <% end %>

  <p class="create-account-note"><%=raw t('home.create_account_note',
                                          :register => link_to(t('home.create_account'), new_user_registration_path, :class => 'coming-soon'),
                                          :login    => link_to(t('home.login_text'), login_path)) %></p>

</div>

app/views/home/map.html.erb
<div class='map-page'>

  <div class="greetings">
    <%= I18n.t('map_page.greetings', :user_name => current_user.first_name).html_safe %>
  </div>

  <div class='address-area'>

    <%= form_for current_user, :url => update_address_path, :html => {:method => :post, :class => 'form-horizontal', :id => 'address_form'} do |f| %>
      <%= f.text_field :address, :id => 'address_autocomplete' %>
      <%= f.hidden_field :city %>
      <%= f.hidden_field :lat  %>
      <%= f.hidden_field :lng  %>

      <%= hidden_field_tag :changed %>
    <% end %>

  </div>

  <div id="map_canvas"></div>
  
  <div id="info_window" style="display:none">

  <%#= link_to I18n.t('map.next_link'), '#', :class => 'btn', :id => 'map-next-link' %>

  <div class="clearfix"></div>

	<div id = "correct_area">
	Is this the correct area?
	</div>
	
	<br><br><br>

  <%#= code below deals with the 'Yes' and 'No' links on the infoWindow.
  They go to the aplication.js file %>

	<div id="no_link">
 	<%= link_to I18n.t('map.no_link'), '#', :class => 'map-no-link' %>
	</div>
	
	<div id="yes_link">
		<%= link_to I18n.t('map.yes_link'), '#', :class => 'map-yes-link' %>

	</div>

</div>

<script type="text/javascript">
  function initialize_google_maps() {



    var midOfIreland = new google.maps.LatLng(53.252069, -7.860718);
    var myOptions = {
      zoom: 7,
      center: midOfIreland,
      mapTypeId: google.maps.MapTypeId.ROADMAP, // ROADMAP, SATELLITE, HYBRID
      streetViewControl: false
    };
    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

    var input = document.getElementById('address_autocomplete');
    var options = {
      types: ['geocode']
    };

   autocomplete = new google.maps.places.Autocomplete(input, options);
    autocomplete.bindTo('bounds', map);
    
    var contentstring = $('#info_window').html();
    
 <%#   var myOptions = {content:'<div id="No_link"><a href=http://www.rosk.com>No</a></div><div id="Yes_link"><a href="#">Yes</a></div>',
    alignBottom:true,
    closeBoxURL: ""  
    };%>
     
var infowindow = new google.maps.InfoWindow({content: contentstring, width:1, height:1});
// for the 'x', to close the infoWindow, we give it the same behaviour as the 'No' link
google.maps.event.addListener(infowindow, 'closeclick', function() {   
  $(".map-no-link").trigger("click");
});  
 
  
   var marker = new google.maps.Marker({
      map: map
    });
    
    

    google.maps.event.addListener(autocomplete, 'place_changed', function() {
      var place = autocomplete.getPlace();
      if (place.geometry.viewport) {
          map.fitBounds(place.geometry.viewport);
      } else {
          map.setCenter(place.geometry.location);
          map.setZoom(11);
      }
      marker.setPosition(place.geometry.location);
      $('#user_lat').val(place.geometry.location.lat());
      $('#user_lng').val(place.geometry.location.lng());
      $('#changed').val('1');

   //   infowindow.setContent(place.name);
      infowindow.open(map, marker);
    });

    <% if current_user.address and current_user.lat %>
      var currentlatlng = new google.maps.LatLng(<%= current_user.lat %>, <%= current_user.lng %>);
      var marker = new google.maps.Marker({map: map, position: currentlatlng});
      map.setCenter(currentlatlng);
      map.setZoom(11);
    <% end %>

  }

  $(function() {
      initialize_google_maps();
  });

</script>

app/views/home/map_backup.html.erb
<div class='map-page'>

  <div class="greetings">
    <%= I18n.t('map_page.greetings', :user_name => current_user.first_name).html_safe %>
  </div>

  <div class='address-area'>

    <%= form_for current_user, :url => update_address_path, :html => {:method => :post, :class => 'form-horizontal', :id => 'address_form'} do |f| %>
      <%= f.text_field :address, :id => 'address_autocomplete' %>
      <%= f.hidden_field :city %>
      <%= f.hidden_field :lat  %>
      <%= f.hidden_field :lng  %>

      <%= hidden_field_tag :changed %>
    <% end %>

  </div>

  <div id="map_canvas"></div>
  
  <div id="info_window" style="display:none">

  <%#= link_to I18n.t('map.next_link'), '#', :class => 'btn', :id => 'map-next-link' %>

  <div class="clearfix"></div>

	<div id = "correct_area">
	Is this the correct area?
	</div>
	
	<br><br><br>
	<div id="no_link">
 	<%= link_to I18n.t('map.no_link'), '#', :class => 'map-no-link' %>
		<!--<a href="#">No</a>-->
	</div>
	
	<div id="yes_link">
		<%= link_to I18n.t('map.yes_link'), '#', :class => 'map-yes-link' %>
		<!--<a href="#">Yes</a>-->
	</div>

</div>
</div>
</div>

<script type="text/javascript">
  function initialize_google_maps() {
    var midOfIreland = new google.maps.LatLng(53.252069, -7.860718);
    var myOptions = {
      zoom: 7,
      center: midOfIreland,
      mapTypeId: google.maps.MapTypeId.ROADMAP // ROADMAP, SATELLITE, HYBRID
      streetViewControl: false
    };
    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

    var input = document.getElementById('address_autocomplete');
    var options = {
      types: ['geocode']
    };

   autocomplete = new google.maps.places.Autocomplete(input, options);
    autocomplete.bindTo('bounds', map);
    
    var contentstring = $('#info_window').html();
    
     
var infowindow = new google.maps.InfoWindow({content: contentstring, width:1, height:1});
  
 
  
   var marker = new google.maps.Marker({
      map: map
    });
    
    

    google.maps.event.addListener(autocomplete, 'place_changed', function() {
      var place = autocomplete.getPlace();
      if (place.geometry.viewport) {
          map.fitBounds(place.geometry.viewport);
      } else {
          map.setCenter(place.geometry.location);
          map.setZoom(11);
      }
      marker.setPosition(place.geometry.location);

      for(i=0; i<place.address_components.length; i++)    
      if(place.address_components[i].types[0] == 'locality')    
      var city = place.address_components[i].short_name;    
      $('#user_city').val(city);
      $('#user_lat').val(place.geometry.location.lat());
      $('#user_lng').val(place.geometry.location.lng());
      $('#changed').val('1');

   //   infowindow.setContent(place.name);
      infowindow.open(map, marker);
    });

    <% if current_user.address and current_user.lat %>
      var currentlatlng = new google.maps.LatLng(<%= current_user.lat %>, <%= current_user.lng %>);
      var marker = new google.maps.Marker({map: map, position: currentlatlng});
      map.setCenter(currentlatlng);
      map.setZoom(11);
    <% end %>

  }

  $(function() {
      initialize_google_maps();
  });

</script>

app/views/home/newmap2.erb
<div class='map-page'>

  <div class="greetings">
    <%= I18n.t('map_page.greetings', :user_name => current_user.first_name).html_safe %>
  </div>

  <div class='address-area'>

    <%= form_for current_user, :url => update_address_path, :html => {:method => :post, :class => 'form-horizontal', :id => 'address_form'} do |f| %>
      <%= f.text_field :address, :id => 'address_autocomplete' %>
      <%= f.hidden_field :lat  %>
      <%= f.hidden_field :lng  %>

      <%= hidden_field_tag :changed %>
    <% end %>

  </div>

  <div id="map_canvas"></div>
  
  <div id="info_window" style="display:none">

  <%#= link_to I18n.t('map.next_link'), '#', :class => 'btn', :id => 'map-next-link' %>

  <div class="clearfix"></div>

	<div id = "correct_area">
	Is this the correct area?
	</div>

	<br><br><br>
	<div id="no_link">
 	<%= link_to I18n.t('map.no_link'), '#', :class => 'map-no-link' %>
		<!--<a href="#">No</a>-->
	</div>

	<div id="yes_link">
		<%= link_to I18n.t('map.yes_link'), '#', :class => 'map-yes-link' %>
		<!--<a href="#">Yes</a>-->
	</div>

</div>

<script type="text/javascript">
  function initialize_google_maps() {
    var midOfIreland = new google.maps.LatLng(53.252069, -7.860718);
    var myOptions = {
      zoom: 7,
      center: midOfIreland,
      mapTypeId: google.maps.MapTypeId.ROADMAP // ROADMAP, SATELLITE, HYBRID
    };
    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

    var input = document.getElementById('address_autocomplete');
    var options = {
      types: ['geocode']
    };

   autocomplete = new google.maps.places.Autocomplete(input, options);
    autocomplete.bindTo('bounds', map);
    
    var contentstring = $('#info_window').html();
    
 <%#   var myOptions = {content:'<div id="No_link"><a href=http://www.rosk.com>No</a></div><div id="Yes_link"><a href="#">Yes</a></div>,
    alignBottom:true,
    closeBoxURL: ""  
    };%>
     
var infowindow = new google.maps.InfoWindow({content: contentstring, width:1, height:1});
  
 
  
   var marker = new google.maps.Marker({
      map: map
    });
    
    

    google.maps.event.addListener(autocomplete, 'place_changed', function() {
      var place = autocomplete.getPlace();
      if (place.geometry.viewport) {
          map.fitBounds(place.geometry.viewport);
      } else {
          map.setCenter(place.geometry.location);
          map.setZoom(11);
      }
      marker.setPosition(place.geometry.location);
      $('#user_lat').val(place.geometry.location.lat());
      $('#user_lng').val(place.geometry.location.lng());
      $('#changed').val('1');

   //   infowindow.setContent(place.name);
      infowindow.open(map, marker);
    });

    <% if current_user.address and current_user.lat %>
      var currentlatlng = new google.maps.LatLng(<%= current_user.lat %>, <%= current_user.lng %>);
      var marker = new google.maps.Marker({map: map, position: currentlatlng});
      map.setCenter(currentlatlng);
      map.setZoom(11);
    <% end %>

  }

  $(function() {
      initialize_google_maps();
  });

</script>

app/views/home/old map.html.erb
<div class='map-page'>

  <div class="greetings">
    <%= I18n.t('map_page.greetings', :user_name => current_user.first_name) %>
  </div>

  <div class='address-area'>

    <%= form_for current_user, :url => update_address_path, :html => {:method => :post, :class => 'form-horizontal', :id => 'address_form'} do |f| %>
      <%= f.text_field :address, :id => 'address_autocomplete' %>
      <%= f.hidden_field :city %>
      <%= f.hidden_field :lat  %>
      <%= f.hidden_field :lng  %>

      <%= hidden_field_tag :changed %>
    <% end %>

  </div>

  <div id="map_canvas"></div>

  <%= link_to I18n.t('map.next_link'), '#', :class => 'btn', :id => 'map-next-link' %>

  <div class="clearfix"></div>

</div>

<script type="text/javascript">
  function initialize_google_maps() {
    var midOfIreland = new google.maps.LatLng(53.252069, -7.860718);
    var myOptions = {
      zoom: 7,
      center: midOfIreland,
      mapTypeId: google.maps.MapTypeId.ROADMAP, // ROADMAP, SATELLITE, HYBRID
      streetViewControl: false
    };
    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

    var input = document.getElementById('address_autocomplete');
    var options = {
      types: ['geocode']
    };

    autocomplete = new google.maps.places.Autocomplete(input, options);
    autocomplete.bindTo('bounds', map);

    var infowindow = new google.maps.InfoWindow();
    var marker = new google.maps.Marker({
      map: map
    });

    google.maps.event.addListener(autocomplete, 'place_changed', function() {
      var place = autocomplete.getPlace();
      if (place.geometry.viewport) {
          map.fitBounds(place.geometry.viewport);
      } else {
          map.setCenter(place.geometry.location);
          map.setZoom(11);
      }
      marker.setPosition(place.geometry.location);

      for(i=0; i<place.address_components.length; i++)
        if(place.address_components[i].types[0] == 'locality')
          var city = place.address_components[i].short_name;
      $('#user_city').val(city);
      $('#user_lat').val(place.geometry.location.lat());
      $('#user_lng').val(place.geometry.location.lng());
      $('#changed').val('1');

      infowindow.setContent(place.name);     
      infowindow.open(map, marker);
    });

    <% if current_user.address and current_user.lat %>
      var currentlatlng = new google.maps.LatLng(<%= current_user.lat %>, <%= current_user.lng %>);
      var marker = new google.maps.Marker({map: map, position: currentlatlng});
      map.setCenter(currentlatlng);
      map.setZoom(11);
    <% end %>

  }

  $(function() {
      initialize_google_maps();
  });

</script>